version: '3'
services:
  db:
    image: mysql
    environment:
      MYSQL_DATABASE: echo_sample
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: password
    ports:
      - 3306:3306
    volumes:
      - ./db/initdb.d:/docker-entrypoint-initdb.d
      - ./db/conf.d:/etc/mysql/conf.d
      - ./log/mysql:/var/log/mysql
  api:
    build: .
    command: go run main.go
    environment:
      DB_USER: root
      DB_PASS: password
      DB_PROTOCOL: tcp(db:3306)
      DB_NAME: echo_sample
    volumes:
      - .:/go/src/app
    ports:
      - 1323:1323
    depends_on:
      - db
    links:
      - db