version: '3'
services:
  db:
    image: mysql
    environment:
      MYSQL_DATABASE: echo_sample
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: password
    ports:
      - '3316:3306'
    volumes:
      - ./db/initdb.d:/docker-entrypoint-initdb.d
      - ./db/conf.d:/etc/mysql/conf.d
      - ./log/mysql:/var/log/mysql
  api:
    build: .
    command: go run main.go
    environment:
      DATABASE_SOURCE: root:password@tcp(db:3306)/echo_sample?parseTime=true
    volumes:
      - .:/app
    ports:
      - 1323:1323
    depends_on:
      - db
    links:
      - db